# Generated by Django 4.2.16 on 2026-06-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='accent_color',
            field=models.CharField(default='#0d9488', max_length=7),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/banners/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='primary_color',
            field=models.CharField(default='#059669', max_length=7),
        ),
    ]
