# Generated by Django 4.2.16 on 2026-06-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
