# Generated by Django 4.2.16 on 2026-06-27 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('orders', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('charge_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sequence', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges_config', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('charge_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculated_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sequence', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charge_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.chargemaster')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='orders.order')),
            ],
            options={
                'ordering': ['sequence', 'name'],
            },
        ),
    ]
