# Generated by Django 4.2.16 on 2026-06-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_chargemaster_ordercharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercharge',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
